### ISSUE TITLE
MFJ - Where is the source code you promised?

### ISSUE THREAD

**Issue by ernestgwilsonii** [hlnurse/rigpi#5]
MFJ - Where is the source code you promised?
73 
W3GUY

**Comment by hlnurse** [comment]
Hi Ernest,

The RigPi software is open source but not currently free,  I own the copyright to RigPi, not MFJ.  I have asked a number of times for help setting up Github for RigPi, with no serious takers.  I'm the only one working on RigPi, so my time is limited.

73, Howard W6HN

**Comment by ernestgwilsonii** [comment]
Thanks for replying Howard!

1.) Which open source license is the software published under?
Trying to understand how it is called open source, but it is an unpublished pay product.

2.How can I help you?
Re: "I have asked a number of times for help setting up Github for RigPi, with no serious takers."

73
Ernest
W3GUY

**Comment by hlnurse** [comment]
Hi Ernest,

Open source means you can edit and modify the source code.  Open source software can be sold.  Free open source software (FOSS) is open source software provided free of charge.

The license for RigPi is GNU General Public License v3.0.  The license is available here in the RigPi Github repository and in the code itself.

An ideal candidate would be someone with experience in setting up a Github repository and who can participate in providing help as Github questions come up.  Experience with HTML5, Ajax, jQuery, and PHP7 is required.  RigPi will need documentation on how to configure your system to run the code.  This includes the html tree plus several other custom utilities that are located outside the tree.

I understand that this is asking a lot, not many folks have the time to help.

Other programs (Fldigi, WSJT-X, etc.) in the RigPi image will not be provided here since they are available from their authors.

Thanks for asking!

--Howard

**Comment by n3glv** [comment]
can hams do a git clone of the rigpi project?
I fully understand all the external apps are not your problem
But the GUI is

**Comment by hlnurse** [comment]
It is possible to clone the RigPi repository now, but there is nothing in it other than the license.  Once RigPi is live on GitHub you will be able to clone it.

--Howard W6HN

**Comment by n3glv** [comment]
I know it's empty. I have been waiting since the product was shown at
Dayton Hamfest on one of the live streams. 3YEARS AGO?

**Comment by geoiii** [comment]
> 2.How can I help you? Re: "I have asked a number of times for help setting up Github for RigPi, with no serious takers."

What do you need done?

Pushing the source code to githhub is not hard. 

I see in this thread and others folks offering to help. 

What help do you need?

George
K5TR

**Comment by hlnurse** [comment]
Hi George,

I'd like to find someone interested in adding to the RigPi code base, and to help manage the GitHub RigPi site.  Thanks for asking.

--Howard W6HN

**Comment by geoiii** [comment]
Ok - without seeing the code it is hard to say if I can or want to help on the code. 

I have never run rigpi - I think I can download the image from MFJ or somewhere and run it.  I do have some remote radios running now - I am using remotehams.com software - but there are a few things I do not like about that software.  The main being that I need to run windows computers to both use it and run the server part.  I am a linux person - my day job is keeping linux machines running and I have avoided doing windows.  But the remotehams software does some things that some other choices does not do - so I am pretty happy with it for the most part.  But having to run windows is not one of them.   Also, it is not open source so there is no hope of even trying to fix anything without the small number of folks working on it.  

Generally folks put the code out there (it is open source) and then folks can find it and if they want to add features or there are bugs to be fixed they can make those changes and submit a PR and whomever if managing the code can merge it into the code base - or not as they see fit.  But without the code it is hard for folks to do any of the above.  

As far as helping manage the github site - what do you see needing to be done in this area?   

I am involved in another project that is on github and there is not anything that I have had to manage around github - but then it is a very small project with only a few folks doing anything right now.  

But what sort of tasks do you think need to be done here on github?  Maybe I can help with those. 

Thanks

**Comment by chazrich** [comment]
I offered, but all I have access to is the OS image. It would take quite a bit of time to dig out all of the code, required packages, and settings. Easier would be to have the actual build files.

**Comment by hlnurse** [comment]
If you have the RigPi image, you can transfer it to an SD card for the Raspberry Pi using something like Win32DiskImager, dotNet Disk Imager, or balenaEtcher.  RigPi is not compiled, it has html5, php7, JavaScript, all in plain text.  (The exception is the graphical UI elements which are compiled from PerfectWidgets.)

--Howard

**Comment by scannerbrightly** [comment]
Hello @hlnurse,

I would like to know the following things about the image supplied RigPi: It appears to be Raspberry Pi OS - Buster, that much we all understand. But what additional software was installed with it? From a apt-get repository or compiled? Which repository or what configuration flags did you use when doing the compiling? Any customized conf or dot files? 

Next, I'd like to know if I can use SignaLink audio connection cables with the RigPi? Places in the forums seems to imply this, but I can't find a definitive HowTo setup document that includes the audio portion. Or, can I use the complete USB SignaLink sound device instead of the audio shield?  How would that change the configuration files listed above? 

Finally, can you link your primary repository for the web interface to this publicly published GitHub source repository so you can make good on your claim that this software is open source? 

Thank you in advance for your time and effort, but there are many who would like to carry it forward, and I'm sure it will help whatever deal you might have with MFJ if a community of people form around your project. Let's move this forward together.

**Comment by hlnurse** [comment]
>

**Comment by hlnurse** [comment]
Hi Seer,

Yes, the RigPi image is based on Buster.  The RigPi server is not compiled with the exception of the UI using Perfect Widgets (a commercial product). There are no conf or dot files.  The RigPi web code is open source except for the widgets. The entire image is available for purchase from MFJ, please see their web site.  In addition, we have made progress in making the web code available on GitHub, thanks to a RigPi user.  Further work is required before it will ready for release.  (The main delay at this point is my limited time...we've just moved from California to Ohio.)

Yes, you can use Signalink (or just about any audio dongle) for audio I/O.  Many of the newer radios have internal CODECs, so no audio hardware is required.  The schematics and cable connections for RigPi are provided in RigPi Help and in the files section on the RigPi forum (https://rigpi.groups.io).  RigPi Help is available on the RigPi web site.

Thanks for your note.  Let me know if you have additional questions.

73, Howard W6HN/8

**Comment by aaron1959** [comment]
So if I have the Image and redistribute it for NO FEE, I can do that legally because you are violating.

hlnurse/rigpi is licensed under the
GNU General Public License v3.0

Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
You have NO LEGAL RECOURSE against anyone GIVING the .IMG file away to others for free!!!!!!!!!

**Comment by chazrich** [comment]
I'm not sure what you mean by "because you are violating". I'm not sure that Howard placed any restrictions on giving the code away, but that would be kind of counterproductive, because the code is under active development, and unless you are part of the Beta and receive the updates then the code could become stale.

**Comment by aaron1959** [comment]
Howard is not a benevelont ham. He's in this to make a buck and I don't blame him, as long as the latest  .img distribution is able to be downloaded for hams I think it's a good thing. So myself and others are going forward to make it available to all hams for free on drop box.

**Comment by downeymj** [comment]
*crickets*
